### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by WimAuw** [vue-pivottable/vue3-pivottable#270]
Frequently refreshing the chart with new data sets will let grow memory. 
Definition

<VuePivottableUi v-if="!pivotReadOnly" id="pivotContainer" :ref="pivotUiRef" :key="pivotKey" 
          :data="pivotData" 
          :rows="pivotRows" 
          :cols="pivotCols" 
          :renderers="pivotRenderers" 
          :rendererName="pivotRendererName"
          :aggregatorName="pivotAggregatorName"
          :rowOrder="pivotRowOrder"
          :colOrder="pivotColOrder"
          :vals="pivotVals"
          :valueFilter="pivotValueFilter"
          :hideFilterBoxOfUnusedAttributes="true"
           />

Refresh triggered by: pivotKey++;
(after setting all pivotXxxxx Fields)

Memory elements that are retained by a JS ref
... multiple instances of: <table class="pvtUI" id="pivotContainer">...</table>
<img width="513" height="695" alt="Image" src="https://github.com/user-attachments/assets/db3f7a45-6cff-485a-9792-ef7dd4f4ba36" />

**Comment by Seungwoo321** [comment]
The `pivotKey++` pattern used in the test is inappropriate for memory leak testing because
  changing the key prop forces Vue to destroy and recreate the entire component, which doesn't
  represent normal usage where pivot tables should preserve user state across data updates. The
  proper approach is to update only the data prop without changing the component key.

Additionally, there's no significant difference between versions:
- v1.1.7: https://codesandbox.io/p/live/4c739959-799b-4e64-8be4-5243128fe3e7
- v1.2.1: https://codesandbox.io/p/live/37d328a9-97a8-4bcd-aff1-7fdb2bb212bd

**Comment by WimAuw** [comment]
I used the pivotKey pattern because updating the properties dit not do it... (I see only the areas and the drag drop fields, no data or row/column fields which were set). The pivotKey++ does show the updated props.

(the pivot is connected to a data grid which can hold different data sets, user can choose the data set and the (previously saved) pivot config to show it in the pivot table... works great! except for memory issue...)

**Comment by Seungwoo321** [comment]
Hi @WimAuw,

Thank you for the clarification about why you need the pivotKey++ pattern.

1. Solution: pivotModel for Your Use Case

Based on your scenario (switching between saved pivot configs for different datasets), the new v-model:pivotModel feature in v1.2.0+ should solve your original problem without needing pivotKey++. The pivotModel ensures UI updates when you load different configurations.

Could you test if pivotModel works for your data grid integration? This should eliminate both the UI update issue and any potential memory concerns.

2. Import Error - Fixed in v1.2.2

Your latest error about missing exports is fixed. Please update to:
  - vue-pivottable@1.2.2
  - @vue-pivottable/plotly-renderer@latest
  - @vue-pivottable/lazy-table-renderer@latest

3. If pivotModel Doesn't Work for You

If pivotModel doesn't solve your use case and you still need the pivotKey++ pattern, could you help us by:
  - Providing a minimal reproduction example
  - Sharing more details about the specific scenarios where pivotModel fails
  - Contributing a PR if you find a solution

 Your real-world use case is valuable for improving the library.
 Please let me know if pivotModel resolves your issue.

 Best regards

**Comment by WimAuw** [comment]
Hi,

thanks for the update... it is now building.
after trying the pivotModel I got the following error:

<img width="415" height="295" alt="Image" src="https://github.com/user-attachments/assets/431a320d-ca59-4c14-8c57-42d725c1411f" />

If I am not mistaken this has to do with the last error I got during the update...  
export 'providePivotData' (imported as 'n0') was not found in 'vue-pivottable' (possible exports: PivotUtilities, Renderer, VuePivottable, VuePivottableUi, default)

**Comment by WimAuw** [comment]
Hi,

The pivotModel works fine, its triggers the update. 
I still have the memory problem, however not what I saw previously (instances of pivotContainer). 

<img width="521" height="122" alt="Image" src="https://github.com/user-attachments/assets/16ab4a74-393d-473c-85da-98b9915ae9a3" />
